#!/bin/bash

free=$(grep MemFree /proc/meminfo | awk '{print $2}');
total=$(grep MemTotal /proc/meminfo | awk '{print $2}');
percentage=$(bc <<< "100 - $free * 100 / $total")
threshold_percentage=65
is_greater_than_threshold=$(bc <<< "$percentage>$threshold_percentage")
message="Close some programs to free RAM"
path_to_file="./notified"

if [ "$is_greater_than_threshold" -eq "1" ];
then
	if [ ! -f "$path_to_file" ]; then
		notify-send "$message";
		touch $path_to_file
	else
		previous_time=$(date -d 'now - 30 seconds' +%s)
		file_time=$(date  -r "$path_to_file" +%s)
		if (( file_time < previous_time )); then
			notify-send "$message";
			touch $path_to_file
		fi
	fi
fi
echo "$percentage%"
